# Generated by Django 5.0.2 on 2024-02-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Freelance', models.BooleanField()),
                ('freetext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('hours_of_support', models.IntegerField()),
                ('awards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=100)),
                ('address_school', models.CharField(max_length=100)),
                ('about_school', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('years_working', models.IntegerField()),
                ('address_of_company', models.CharField(max_length=100)),
                ('section_1', models.CharField(max_length=100)),
                ('section_2', models.CharField(max_length=100)),
                ('section_3', models.CharField(max_length=100)),
                ('section_4', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('years_working2', models.IntegerField()),
                ('address_of_company2', models.CharField(max_length=100)),
                ('section_12', models.CharField(max_length=100)),
                ('section_22', models.CharField(max_length=100)),
                ('section_32', models.CharField(max_length=100)),
                ('section_42', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('facebook', models.URLField()),
                ('Linkedin', models.URLField()),
                ('Github', models.URLField()),
                ('Website', models.URLField()),
                ('Designed_by', models.CharField(max_length=100)),
                ('Designer', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest1', models.CharField(max_length=100)),
                ('interest2', models.CharField(max_length=100)),
                ('interest3', models.CharField(max_length=100)),
                ('interest4', models.CharField(max_length=100)),
                ('interest5', models.CharField(max_length=100)),
                ('interest6', models.CharField(max_length=100)),
                ('interest7', models.CharField(max_length=100)),
                ('interest8', models.CharField(max_length=100)),
                ('interest9', models.CharField(max_length=100)),
                ('interest10', models.CharField(max_length=100)),
                ('interest11', models.CharField(max_length=100)),
                ('interest12', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=100)),
                ('skill1value', models.IntegerField()),
                ('skill2', models.CharField(max_length=100)),
                ('skill2value', models.IntegerField()),
                ('skill3', models.CharField(max_length=100)),
                ('skill3value', models.IntegerField()),
                ('skill4', models.CharField(max_length=100)),
                ('skill4value', models.IntegerField()),
                ('skill5', models.CharField(max_length=100)),
                ('skill5value', models.IntegerField()),
                ('skill6', models.CharField(max_length=100)),
                ('skill6value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=100)),
                ('address_university', models.CharField(max_length=100)),
                ('about_university', models.CharField(max_length=100)),
            ],
        ),
    ]
