# Generated by Django 5.0.2 on 2024-02-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0002_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
