# Generated by Django 5.0.2 on 2024-02-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0003_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/personal_portfolio/static/img/portfolio')),
                ('url', models.URLField()),
            ],
        ),
    ]
