# Generated by Django 5.0.2 on 2024-02-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
