# Generated by Django 5.0.2 on 2024-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_1', models.CharField(max_length=100)),
                ('service_1_description', models.TextField()),
                ('service_2', models.CharField(max_length=100)),
                ('service_2_description', models.TextField()),
                ('service_3', models.CharField(max_length=100)),
                ('service_3_description', models.TextField()),
                ('service_4', models.CharField(max_length=100)),
                ('service_4_description', models.TextField()),
                ('service_5', models.CharField(max_length=100)),
                ('service_5_description', models.TextField()),
                ('service_6', models.CharField(max_length=100)),
                ('service_6_description', models.TextField()),
            ],
        ),
    ]
