# Generated by Django 5.0.2 on 2024-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0009_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_1', models.CharField(max_length=100)),
                ('project_1_description', models.TextField()),
                ('project_2', models.CharField(max_length=100)),
                ('project_2_description', models.TextField()),
                ('project_3', models.CharField(max_length=100)),
                ('project_3_description', models.TextField()),
                ('project_1_url', models.URLField()),
                ('project_2_url', models.URLField()),
                ('project_3_url', models.URLField()),
            ],
        ),
    ]
